<?php

/**
 * This file is part of Cria.
 * Cria is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * Cria is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with Cria. If not, see <https://www.gnu.org/licenses/>.
 *
 * @package    local_cria
 * @author     Patrick Thibaudeau
 * @copyright  2024 onwards York University (https://yorku.ca)
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */


/*
 * Author: Admin User
 * Create Date: 27-07-2023
 * License: LGPL 
 * 
 */

namespace local_cria;

use core\notification;
use local_cria\criabot;
use local_cria\crud;
use local_cria\criabdex;
use local_cria\logs;
use local_cria\keywords;
use local_cria\embed;
use local_cria\file;
use local_cria\criaparse;
use local_cria\bot;


class intent extends crud
{


    /**
     *
     * @var int
     */
    private $id;

    /**
     *
     * @var string
     */
    private $name;

    /**
     *
     * @var string
     */
    private $description;

    /**
     *
     * @var int
     */
    private $bot_id;

    /**
     *
     * @var int
     */
    private $is_default;

    /**
     *
     * @var string
     */
    private $bot_api_key;

    /**
     *
     * @var int
     */
    private $published;

    /**
     *
     * @var string
     */
    private $lang;

    /**
     * @var string
     */
    private $faculty;

    /**
     * @var string
     */
    private $program;

    /**
     *
     * @var int
     */
    private $usermodified;

    /**
     *
     * @var int
     */
    private $timecreated;

    /**
     *
     * @var int
     */
    private $timemodified;

    /**
     *
     * @var string
     */
    private $table;


    /**
     *
     *
     */
    public function __construct($id = 0)
    {
        global $CFG, $DB, $DB;

        $this->table = 'local_cria_intents';
        parent::set_table($this->table);

        if ($id) {
            $this->id = $id;
            parent::set_id($this->id);
            $result = $this->get_record($this->table, ['id' => $this->id]);
        } else {
            $result = new \stdClass();
            $this->id = 0;
            parent::set_id($this->id);
        }

        $this->name = $result->name ?? '';
        $this->description = $result->description ?? '';
        $this->bot_id = $result->bot_id ?? 0;
        $this->is_default = $result->is_default ?? 0;
        $this->bot_api_key = $result->bot_api_key ?? '';
        $this->published = $result->published ?? 0;
        $this->lang = $result->lang ?? '';
        $this->faculty = $result->faculty ?? '';
        $this->program = $result->program ?? '';
        $this->usermodified = $result->usermodified ?? 0;
        $this->timecreated = $result->timecreated ?? 0;
        $this->timemodified = $result->timemodified ?? 0;
    }

    /**
     * @param $data
     * @return int
     * @throws \dml_exception
     */
    public function insert_record($data): int
    {
        global $DB;
        $data = $data;
        $new_intent_id = parent::insert_record($data); // TODO: Change the autogenerated stub

        if ($data->published) {
            $NEW_INTENT = new intent($new_intent_id);
            $BOT = new bot($NEW_INTENT->get_bot_id());
            if (!$BOT->has_valid_model_links()) {
                \core\notification::error(get_string('sync_bot_missing_models', 'local_cria'));
                return $new_intent_id;
            }
            $result = $NEW_INTENT->create_intent_on_bot_server();
            if (api_response::is_success($result) && !empty($result->bot_api_key)) {
                $params = new \stdClass();
                $params->id = $new_intent_id;
                $params->bot_api_key = $result->bot_api_key;
                $DB->update_record('local_cria_intents', $params);
            } else {
                \core\notification::error(api_response::error_message(
                    $result,
                    get_string('sync_bot_push_failed', 'local_cria')
                ));
            }
        }
        return $new_intent_id;
    }

    public function update_record($data): int
    {
        parent::update_record($data); // TODO: Change the autogenerated stub

        if ($data->published) {
            $this->update_intent_on_bot_server();
        }

        return $this->id;
    }

    /**
     * Does the default intetn exist for this bot?
     * @param $bot_id
     * @return bool
     * @throws \dml_exception
     */
    public function default_intent_exists($bot_id)
    {
        global $DB;
        return $DB->record_exists('local_cria_intents', ['bot_id' => $bot_id, 'is_default' => 1]);
    }

    /**
     * Create example questions
     * @param $question_id
     * @return void
     * @throws \dml_exception
     */
    public function generate_example_questions($question_id)
    {
        global $DB, $USER;

        $QUESTION = new question($question_id);
        $QUESTION->generate_example_questions($this->id, $question_id);
    }

    /**
     * Translate question
     * @param $question_text
     * @param $language
     * @return mixed
     * @throws \dml_exception
     */
    public function translate_question($question_text, $language)
    {
        $QUESTION = new question();
        $results = $QUESTION->translate_question($this->id, $question_text, $language);
        return $results;
    }

    /**
     * Insert into logs
     * @param $results
     * @param $prompt
     * @return void
     * @throws \dml_exception
     */
    public function insert_log_record($results, $prompt)
    {
        $agent = $results->agent_response ?? new \stdClass();
        $token_usage = gpt::extract_usage($agent);

        $prompt_tokens = $token_usage->prompt_tokens ?? 0;
        $completion_tokens = $token_usage->completion_tokens ?? 0;
        $total_tokens = $token_usage->total_tokens ?? 0;

        $cost = gpt::_get_cost($this->bot_id, $prompt_tokens, $completion_tokens);
        logs::insert(
            $this->bot_id,
            $prompt,
            gpt::extract_content($agent),
            $prompt_tokens,
            $completion_tokens,
            $total_tokens,
            $cost,
            '');
    }

    /**
     * Return the id of the intent
     */
    public function get_id(): int
    {
        return $this->id;
    }

    /*
     *  Return the name of the intent
     */
    public function get_name(): string
    {
        return $this->name;
    }

    /**
     * Return the description of the intent
     */
    public function get_description(): string
    {
        return $this->description;
    }

    /**
     * @return Int bot_id
     */
    public function get_bot_id(): int
    {
        return $this->bot_id;
    }

    /**
     * @return String bot_api_key
     */
    public function get_bot_api_key(): string
    {
        return $this->bot_api_key;
    }

    /**
     * Get bot name
     * @return string
     */
    public function get_bot_name(): string
    {
        $BOT = new bot($this->bot_id);
        if ($BOT->use_bot_server()) {
            return $this->bot_id . '-' . $this->id;
        }
        return (string) $this->bot_id;
    }

    /**
     * @return int default
     */
    public function get_is_default(): int
    {
        return $this->is_default;
    }

    /**
     * @return int publish
     */
    public function get_published(): int
    {
        return $this->published;
    }

    /**
     * @return string lang
     */
    public function get_lang(): string
    {
        return $this->lang;
    }

    /**
     * @return string faculty
     */
    public function get_faculty(): string
    {
        return $this->faculty;
    }

    /**
     * @return string program
     */
    public function get_program(): string
    {
        return $this->program;
    }

    /**
     *  Intent always uses bot parameters.
     *  This function returns the bot parameters in json format
     * @return String
     */
    public function get_bot_parameters_json(): string
    {
        $BOT = new \local_cria\bot($this->bot_id);
        $params = $BOT->get_bot_parameters_json();
        $params = json_decode($params);
        $system_message = $params->system_message;
        $system_message .= 'This bot is used for users asking questions with the following attributes: ';
        $system_message .= 'language: ' . $this->lang;
        if ($this->faculty) {
            $system_message .= ', faculty: ' . $this->faculty;
        }
        if ($this->program) {
            $system_message .= ', program: ' . $this->program;
        }
        $params->system_message = $system_message;

        return json_encode($params);
    }

    /**
     * @return array|false
     * @throws \dml_exception
     */
    public function get_questions(): mixed
    {
        $QUESTIONS = new questions($this->id);
        return $QUESTIONS->get_questions();
    }

    /**
     * Publish question to bot server
     * @return text
     * @throws \dml_exception
     */
    public function publish_question($question_id)
    {
        global $DB;

        // Get the question
        $question = $DB->get_record('local_cria_question', ['id' => $question_id]);
        // Get keywords and synonyms
        $KEYWORDS = new keywords();
        $keywords = $KEYWORDS->get_keywords_for_criabot($question->keywords);
        // Get all related questions
        $related_prompts = [];
        if (!empty($question->related_questions)) {
            $related_questions = json_decode($question->related_questions);
            foreach ($related_questions as $related_question) {
                // Explode on pipe
                ;
                $related_prompts[] = [
                    'label' => $related_question->label,
                    'prompt' => $related_question->prompt
                ];
            }
        }
        // Get all question examples
        $question_examples = $DB->get_records(
            'local_cria_question_example',
            [
                'questionid' => $question_id,
            ],
            'id'
        );
        // Put questions in a comma seperated string
        $question_examples_string = $question->value;
        foreach ($question_examples as $question_example) {
            $question_examples_string .= ',' . $question_example->value;
        }
        $return_generated_answer = $question->generate_answer ? true : false;
        // Create data set
        $data = array(
            'file_contents' => array(
                'questions' => explode(',', $question_examples_string),
                'answer' => strip_tags($question->answer),
                'llm_reply' => $return_generated_answer,
                'related_prompts' => $related_prompts,
            ),
            'file_metadata' => array(
                'keywords' => $keywords,
                'question_id' => $question_id,
                'return_generated_answer' => $return_generated_answer,
            )
        );

        // publish question to bot server
        if ($question->document_name) {
            $data['file_name'] = $question->document_name;
            $question_content = criabot::question_update($this->get_bot_name(), $data);
        } else {
            $question_content = criabot::question_create($this->get_bot_name(), $data);
        }
        if (!is_object($question_content)) {
            api_response::notify_error(
                $question_content,
                get_string('sync_content_push_failed', 'local_cria')
            );
            return get_string('sync_content_push_failed', 'local_cria');
        }

        // Update question indexed
        if (api_response::is_success($question_content)) {
            $DB->set_field(
                'local_cria_question',
                'published',
                1,
                ['id' => $question_id]
            );
            // Only add document name if it does not exist
            if (!$question->document_name) {
                $DB->set_field(
                    'local_cria_question',
                    'document_name',
                    $question_content->document_name,
                    ['id' => $question_id]
                );
            }
            // Update all question examples indexed
            foreach ($question_examples as $question_example) {
                $DB->set_field(
                    'local_cria_question_example',
                    'indexed',
                    1,
                    ['id' => $question_example->id]
                );
            }
            return 200;
        }

        api_response::notify_error($question_content, get_string('sync_content_push_failed', 'local_cria'));
        api_response::log_issue('Criabot question publish ' . $this->get_bot_name(), $question_content);
        return api_response::error_message($question_content, get_string('sync_content_push_failed', 'local_cria'));
    }

    /**
     * Return user id
     */
    public function get_usermodified(): int
    {
        return $this->usermodified;
    }

    /**
     * Return time created
     */
    public function get_timecreated(): int
    {
        return $this->timecreated;
    }

    /**
     * Return time modified
     */
    public function get_timemodified(): int
    {
        return $this->timemodified;
    }

    /**
     * @param \local_cria\intent: bigint (18)
     */
    public function set_id($id): void
    {
        $this->id = $id;
    }

    /**
     * @param \local_cria\intent: varchar (255)
     */
    public function set_name($name): void
    {
        $this->name = $name;
    }

    /**
     * @param \local_cria\intent: longtext (-1)
     */
    public function set_description($description): void
    {
        $this->description = $description;
    }

    /**
     * @param $public
     * @return void
     */
    public function set_pulish($publish): void
    {
        $this->publish = $publish;
    }


    /**
     * @return void
     * @throws \coding_exception
     * @throws \dml_exception
     */
    public function create_intent_on_bot_server()
    {
        $bot_name = $this->get_bot_name();
        $result = criabot::bot_create((string)$bot_name, $this->get_bot_parameters_json());
        return $result;
    }

    /**
     * @return void
     * @throws \coding_exception
     * @throws \dml_exception
     */
    public function update_intent_on_bot_server(bool $notify = true)
    {
        $bot_name = $this->get_bot_name();
        $bot_exists = criabot::bot_about((string)$bot_name);

        $BOT = new bot($this->bot_id);
        if (!$BOT->has_valid_model_links()) {
            if ($notify) {
                \core\notification::error(get_string('sync_bot_missing_models', 'local_cria'));
            }
            return false;
        }

        if (!is_object($bot_exists) || !isset($bot_exists->status)) {
            if ($notify) {
                api_response::notify_error($bot_exists, get_string('sync_criabot_unreachable', 'local_cria'));
            }
            api_response::log_issue('Criabot intent about ' . $bot_name, $bot_exists);
            return false;
        }

        if ((int) $bot_exists->status === 404) {
            $result = criabot::bot_create((string)$bot_name, $this->get_bot_parameters_json());
        } else {
            $result = criabot::bot_update((string)$bot_name, $this->get_bot_parameters_json());
        }

        if (api_response::is_success($result)) {
            return true;
        }

        if ($notify) {
            api_response::notify_error($result, get_string('sync_bot_push_failed', 'local_cria'));
        }
        api_response::log_issue('Criabot intent push ' . $bot_name, $result);
        return false;
    }

    /**
     * Retunr all files associated with this intent
     * @return array
     * @throws \dml_exception
     */
    public function get_files()
    {
        global $DB;
        $files = $DB->get_records('local_cria_files', ['intent_id' => $this->id]);
        return $files;
    }

    /**
     * Delete intent on both bot server and local database
     * @return bool
     */
    public function delete_record(): bool
    {
        // Delete bot on bot server
        criabot::bot_delete($this->get_bot_name());
        // Delete embed
        criaembed::manage_delete($this->id);
        return parent::delete_record(); // TODO: Change the autogenerated stub
    }

    /**
     * Check file state
     * @return int
     * @throws \dml_exception
     */
    public function check_file_state()
    {
        global $DB;
        $file_state_sql = "SELECT COUNT(*) as count FROM {local_cria_files} WHERE intent_id = ? AND indexed IN (?,?)";
        $file_state = $DB->get_record_sql($file_state_sql, [
            $this->id,
            file::INDEXING_PENDING,
            file::INDEXING_STARTED
        ]);

        return $file_state->count;
    }

    /**
     * Queue background indexing and run it immediately in the current request.
     *
     * @param int $intentid
     * @param int $fileid
     * @return void
     */
    public static function schedule_index_file(int $intentid, int $fileid): void
    {
        global $USER;

        $task = new \local_cria\task\index_files_adhoc();
        if (!empty($USER->id)) {
            $task->set_userid($USER->id);
        }
        $task->set_custom_data((object) [
            'intent_id' => $intentid,
            'file_id' => $fileid,
        ]);
        \core\task\manager::queue_adhoc_task($task);

        try {
            (new self($intentid))->index_files($fileid);
        } catch (\Throwable $e) {
            debugging('local_cria immediate file indexing failed: ' . $e->getMessage(), DEBUG_DEVELOPER);
        }
    }

    /**
     * Index all pending files for this intent.
     *
     * @return int Number of files processed.
     * @throws \dml_exception
     */
    public function index_pending_files(): int
    {
        global $DB;

        $pending = $DB->get_records('local_cria_files', [
            'intent_id' => $this->id,
            'indexed' => file::INDEXING_PENDING,
        ], 'id ASC');

        $processed = 0;
        foreach ($pending as $pendingfile) {
            if ($this->index_files((int) $pendingfile->id)) {
                $processed++;
            }
        }

        return $processed;
    }

    /**
     * Index files for this intent
     * @param int $file_id
     * @return bool
     * @throws \dml_exception
     */
    public function index_files($file_id)
    {
        global $DB, $USER, $CFG;

        $fileid = (int) $file_id;
        if ($fileid <= 0) {
            return false;
        }

        $FILE = new file();
        $file = $DB->get_record('local_cria_files', [
            'id' => $fileid,
            'intent_id' => $this->id,
            'indexed' => $FILE::INDEXING_PENDING,
        ]);
        if (!$file) {
            return false;
        }

        try {
            return $this->index_pending_file_record($file);
        } catch (\Throwable $e) {
            $DB->update_record('local_cria_files', (object) [
                'id' => $file->id,
                'indexed' => $FILE::INDEXING_FAILED,
                'error_message' => json_encode([
                    'message' => 'Indexing failed with an unexpected error.',
                    'detail' => $e->getMessage(),
                ], JSON_PRETTY_PRINT),
                'timemodified' => time(),
                'usermodified' => $USER->id ?? 0,
            ]);
            debugging('local_cria index_files failed for file ' . $fileid . ': ' . $e->getMessage(), DEBUG_DEVELOPER);
            return false;
        }
    }

    /**
     * @param \stdClass $file
     * @return bool
     * @throws \dml_exception
     */
    private function index_pending_file_record(\stdClass $file): bool
    {
        global $DB, $USER, $CFG;

        $FILE = new file();
        $context = \context_system::instance();

        $criadexfiles = criadex::list_document_file_names($this->get_bot_id());
        if (in_array($file->name, $criadexfiles, true)) {
            $DB->update_record('local_cria_files', (object) [
                'id' => $file->id,
                'indexed' => $FILE::INDEXING_COMPLETE,
                'timemodified' => time(),
                'usermodified' => $USER->id ?? 0,
            ]);
            return true;
        }

        $BOT = new bot($this->get_bot_id());
        $path = $CFG->dataroot . '/temp/cria/' . $this->id;
        base::create_directory_if_not_exists($CFG->dataroot . '/temp/cria');
        base::create_directory_if_not_exists($path);

        $fs = get_file_storage();
        $moodlefile = $fs->get_file($context->id, 'local_cria', 'content', $this->id, '/', $file->name);
        if (!$moodlefile) {
            $DB->update_record('local_cria_files', (object) [
                'id' => $file->id,
                'indexed' => $FILE::INDEXING_FAILED,
                'error_message' => json_encode(['message' => 'File not found in Moodle storage.'], JSON_PRETTY_PRINT),
                'timemodified' => time(),
                'usermodified' => $USER->id ?? 0,
            ]);
            return false;
        }

        $DB->update_record('local_cria_files', (object) [
            'id' => $file->id,
            'indexed' => $FILE::INDEXING_STARTED,
            'timemodified' => time(),
            'usermodified' => $USER->id ?? 0,
        ]);

        $botparsingstrategy = $BOT->get_parse_strategy();
        $filename = $moodlefile->get_filename();
        $filetype = $FILE->get_file_type_from_mime_type($moodlefile->get_mimetype());
        if ($filetype === '') {
            $filetype = $FILE->get_file_type_from_filename($filename);
        }
        if ($filetype === '' && !empty($file->file_type)) {
            $filetype = $file->file_type;
        }

        $mimetype = $moodlefile->get_mimetype();
        if ($mimetype === '' || $mimetype === 'application/octet-stream') {
            $mimetype = $FILE->get_mime_type_for_parsing($filetype, $filename);
        }

        $moodlefile->copy_content_to($path . '/' . $filename);
        if ($file->parsingstrategy != $BOT->get_parse_strategy()) {
            $botparsingstrategy = $file->parsingstrategy;
        }

        $botparameters = json_decode($BOT->get_bot_parameters_json());
        $llmmodelid = is_object($botparameters) ? (int) ($botparameters->llm_model_id ?? 0) : 0;
        $embeddingmodelid = is_object($botparameters) ? (int) ($botparameters->embedding_model_id ?? 0) : 0;
        $originalstrategy = criaparse::set_parsing_strategy_based_on_file_type(
            $filetype,
            $botparsingstrategy
        );
        $parsingstrategy = criaparse::resolve_indexing_strategy(
            $filetype,
            $botparsingstrategy,
            $llmmodelid,
            $embeddingmodelid
        );

        if ($parsingstrategy !== 'PARAGRAPH') {
            if (
                !is_object($botparameters)
                || empty($botparameters->llm_model_id)
                || empty($botparameters->embedding_model_id)
            ) {
                $DB->update_record('local_cria_files', (object) [
                    'id' => $file->id,
                    'indexed' => $FILE::INDEXING_FAILED,
                    'error_message' => json_encode([
                        'message' => get_string('sync_bot_missing_models', 'local_cria'),
                    ], JSON_PRETTY_PRINT),
                    'timemodified' => time(),
                    'usermodified' => $USER->id ?? 0,
                ]);
                return false;
            }
        }

        $results = criaparse::execute(
            $parsingstrategy === 'PARAGRAPH' ? 0 : $botparameters->llm_model_id,
            $parsingstrategy === 'PARAGRAPH' ? 0 : $botparameters->embedding_model_id,
            $parsingstrategy,
            $path . '/' . $filename,
            $mimetype
        );

        if ($results === null || (int) ($results['status'] ?? 0) !== 200) {
            $errormessage = $results['message'] ?? 'CriaParse request failed or returned no response.';
            if (!empty($results['error'])) {
                $errormessage .= ' ' . $results['error'];
            }
            $DB->update_record('local_cria_files', (object) [
                'id' => $file->id,
                'indexed' => $FILE::INDEXING_FAILED,
                'error_message' => json_encode(
                    $results ?? ['message' => 'CriaParse request failed or returned no response.'],
                    JSON_PRETTY_PRINT
                ),
                'timemodified' => time(),
                'usermodified' => $USER->id ?? 0,
            ]);
            api_response::log_issue(
                'CriaParse file ' . $filename . ' (intent ' . $this->id . ')',
                (object) [
                    'status' => $results['status'] ?? 0,
                    'message' => $errormessage,
                ]
            );
            return false;
        }

        $nodes = $results['nodes'];
        $upload = $FILE->upload_nodes_to_indexing_server($this->get_bot_name(), $nodes, $filename, $filetype, false);
        $contentdata = (object) [
            'id' => $file->id,
            'nodes' => json_encode($nodes, JSON_PRETTY_PRINT),
            'timemodified' => time(),
            'usermodified' => $USER->id ?? 0,
        ];

        if (!api_response::is_success($upload)) {
            $contentdata->indexed = $FILE::INDEXING_FAILED;
            $contentdata->error_message = api_response::error_message(
                $upload,
                get_string('sync_index_upload_failed', 'local_cria')
            );
            $DB->update_record('local_cria_files', $contentdata);
            api_response::log_issue(
                'Criabot document upload ' . $filename . ' (intent ' . $this->id . ')',
                $upload
            );
            return false;
        }

        $contentdata->indexed = $FILE::INDEXING_COMPLETE;
        $DB->update_record('local_cria_files', $contentdata);
        return true;
    }

}